# Site settings
title: "Green Computing"
description: "Study group of the Studienstiftung des deutschen Volkes in Leysin."

# Collections to include
collections:
  - topics
  - devices
  - references
  - instructors

gems:
  - jekyll-feed

# Social networks usernames
social:
  - title: github
    url: https://github.com/greeniot

# Postal address (add as many lines as necessary)
address:
  - line: Dr. Florian Rappl
  - line: Heiglhofstr. 11
  - line: 81377 München

# Build settings
markdown: kramdown
permalink: pretty
